version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pdf_merge_backend
    ports:
      - "5000:5000"

  flutter_web:
    build: ./flutter_app
    container_name: pdf_merge_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
